# no need to create network

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data" #double quote
    ports:
      - "5432:5432" #double quote
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80" #double quote
  
  dataingestion:
    image: taxi_ingest:v001
    command:
      [
        "--user", "root",
        "--password", "root",
        "--host", "pgdatabase",
        "--port", "5432",
        "--database_name", "ny_taxi",
        "--table_name", "yellow_taxi_trips",
        "--url", "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"
      ]
