# no need to create network

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data" #double quote
    ports:
      - "5432:5432" #double quote
    networks:
      - airflow

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   volumes:
  #     # - pgadmin_data:/var/lib/pgadmin
  #     - ./pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "8080:80" #double quote
  
  dataingestion:
    image: taxi_ingest:v002 #2019 ingestion
    command:
      [
        "--user", "root",
        "--password", "root",
        "--host", "pgdatabase",
        "--port", "5432",
        "--database_name", "ny_taxi",
        "--table_name", "yellow_taxi_trips_oct2019",
        "--trips_url", "wget https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz",
        "--zones_url", "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv"
      ]
    depends_on:
      - pgdatabase

    networks:
      - airflow

# volumes:
#   pgadmin_data:

networks:
  airflow:
    external:
      name: airflow_default



